---
- name: Install Docker
  apt:
    name: docker.io
    state: present
    update_cache: yes

- name: Install Docker Compose
  apt:
    name: docker-compose
    state: present

- name: Enable Docker service
  systemd:
    name: docker
    enabled: true
    state: started

- name: Pull Ansible Semaphore Docker image
  docker_image:
    name: ansiblesemaphore/semaphore
    source: pull

- name: Run Ansible Semaphore Docker container
  community.docker.docker_container:
    name: semaphore
    image: ansiblesemaphore/semaphore
    state: started
    ports:
      - "3000:3000"
    env:
      DB_DIALECT: "postgres"
      DB_HOST: "localhost"
      DB_PORT: "5432"
      DB_USER: "semaphore_user"
      DB_PASS: "password"
      DB_NAME: "semaphore_db"
    restart_policy: always

